version: "3.7"

services:
  eth-pokhar:
    build:
      context: ./
      dockerfile: Dockerfile
    init: true
    environment:
      - LOG_LEVEL=${LOG_LEVEL}
      - EL_ENDPOINT=${EL_ENDPOINT}
      - DB_URL=${DB_URL}
      - WORKER_NUM=${WORKER_NUM}
      - ALCHEMY_URL=${ALCHEMY_URL}
      - WHALE_THRESHOLD=${WHALE_THRESHOLD}
      - ONLY_DEPOSITS=${ONLY_DEPOSITS:-false}
    network_mode: "host"
    depends_on:
      db:
        condition: service_healthy
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5
    entrypoint: ["sh", "./run.sh"]

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - ./app-data/:/var/lib/postgresql/data/
    ports:
      - "127.0.0.1:${LOCAL_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
