name: Issue Labeler

on:
  issues:
    types: [opened, edited]

permissions:
  contents: read

jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    strategy:
      fail-fast: false
      matrix:
        template:
          - 1-bug-report.yml
          - 2-feature-request.yml
          - 3-performance.yml
          - 5-task.yml
    steps:
      - uses: actions/checkout@v4

      - name: Parse issue form
        id: issue-parser
        uses: stefanbuck/github-issue-parser@v3
        with:
          template-path: .github/ISSUE_TEMPLATE/${{ matrix.template }}

      - name: Apply labels from form dropdowns
        uses: redhat-plumbers-in-action/advanced-issue-labeler@v3
        with:
          issue-form: ${{ steps.issue-parser.outputs.jsonString }}
          template: ${{ matrix.template }}
          token: ${{ secrets.GITHUB_TOKEN }}
